apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "jena-es.fullname" . }}
  labels:
    app: {{ template "jena-es.name" . }}
    chart: {{ template "jena-es.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  api-key: {{ .Values.jena.apiKey | b64enc | quote }}
