apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "addis-core.fullname" . }}
  labels:
    app: {{ template "addis-core.name" . }}
    chart: {{ template "addis-core.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  jena-api-key: {{ .Values.jena.apiKey | b64enc | quote }}
  patavi-api-key: {{ .Values.patavi.apiKey | b64enc | quote }}
  google-key: {{ .Values.addis.googleKey | b64enc | quote }}
  google-secret: {{ .Values.addis.googleSecret | b64enc | quote }}
  database-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
